### ISSUE TITLE
Console: window not found -> not a browser environment

### ISSUE THREAD

**Issue by muriloqr** [eastolfi/MongoPortable#18]
Is there a way to hide this log (window not found -> not a browser environment)?

I had already use options an entry to the logger like #16 but doesnt work

**Comment by eastolfi** [comment]
Hi,

The new version 2.0.3 cames with the [fix of the library raising this log](https://github.com/EastolfiWebDev/JSW-Logger/issues/7).

Please, can you do an update to see if everything is okay? Thanks :)

**Comment by muriloqr** [comment]
Thanks!
