### ISSUE TITLE
#remove is always limit=15

### ISSUE THREAD

**Issue by ghost** [eastolfi/MongoPortable#6]
Hi

**Scenario**
Collection.remove({}).

**Expectation**
Collection.find({}).count() == 0

**Reality**
Collection.find({}).count() has only been reduced by 15.
The reason seems to be that #remove uses #find, but without any way to pass #find a limit.
The default value is 15, this seems at least, so I am not able to clear my collection.

Could you please check this out ?
Or am I wrong ?
Regards

**Comment by eastolfi** [comment]
Hi! First, I'm glad that you gave this repo a try :)

So, you're totally right. I'm gonna fix it within the next days.

Thank you for found it ;)

**Comment by eastolfi** [comment]
Hi, thanks for checking it. The fix it's going to be addressed by default in the version 2.0.0, which is almost ready.

**Comment by eastolfi** [comment]
@ArThoX The 2.0.0 it's been published in the npm repository.
